export const TYPES = {
    FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
    FETCH_TESTIMONIALS_REQUEST: 'FETCH_TESTIMONIALS_REQUEST',
    FETCH_TESTIMONIALS_SUCCESS: 'FETCH_TESTIMONIALS_SUCCESS',
    FETCH_TESTIMONIALS_FAILURE: 'FETCH_TESTIMONIALS_FAILURE',

    POST_SUBSCRIPTION: 'POST_SUBSCRIPTION',
    POST_SUBSCRIPTION_REQUEST: 'POST_SUBSCRIPTION_REQUEST',
    POST_SUBSCRIPTION_SUCCESS: 'POST_SUBSCRIPTION_SUCCESS',
    POST_SUBSCRIPTION_FAILURE: 'POST_SUBSCRIPTION_FAILURE',

    POST_RESUME: 'POST_RESUME',
    POST_RESUME_REQUEST: 'POST_RESUME_REQUEST',
    POST_RESUME_SUCCESS: 'POST_RESUME_SUCCESS',
    POST_RESUME_FAILURE: 'POST_RESUME_FAILURE',

    POST_CONTACT_FORM: 'POST_CONTACT_FORM',
    POST_CONTACT_FORM_REQUEST: 'POST_CONTACT_FORM_REQUEST',
    POST_CONTACT_FORM_SUCCESS: 'POST_CONTACT_FORM_SUCCESS',
    POST_CONTACT_FORM_FAILURE: 'POST_CONTACT_FORM_FAILURE',
}
export const action = (type, payload = {}) => {
    return { type, payload }
}

export const fetchTestimonials = () => action(TYPES.FETCH_TESTIMONIALS)
export const postSubscription = (data) => action(TYPES.POST_SUBSCRIPTION, { data })
export const postResume = (data) => action(TYPES.POST_RESUME, { data })
export const postContactForm = (data) => action(TYPES.POST_CONTACT_FORM, { data })
