export const TYPES = {
    FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
    FETCH_TESTIMONIALS_REQUEST: 'FETCH_TESTIMONIALS_REQUEST',
    FETCH_TESTIMONIALS_SUCCESS: 'FETCH_TESTIMONIALS_SUCCESS',
    FETCH_TESTIMONIALS_FAILURE: 'FETCH_TESTIMONIALS_FAILURE',

    FETCH_BANNER: 'FETCH_BANNER',
    FETCH_BANNER_REQUEST: 'FETCH_BANNER_REQUEST',
    FETCH_BANNER_SUCCESS: 'FETCH_BANNER_SUCCESS',
    FETCH_BANNER_FAILURE: 'FETCH_BANNER_FAILURE',

    FETCH_BLOG: 'FETCH_BLOG',
    FETCH_BLOG_REQUEST: 'FETCH_BLOG_REQUEST',
    FETCH_BLOG_SUCCESS: 'FETCH_BLOG_SUCCESS',
    FETCH_BLOG_FAILURE: 'FETCH_BLOG_FAILURE',

    FETCH_CLIENT: 'FETCH_CLIENT',
    FETCH_CLIENT_REQUEST: 'FETCH_CLIENT_REQUEST',
    FETCH_CLIENT_SUCCESS: 'FETCH_CLIENT_SUCCESS',
    FETCH_CLIENT_FAILURE: 'FETCH_CLIENT_FAILURE',

    FETCH_STATISTICS: 'FETCH_STATISTICS',
    FETCH_STATISTICS_REQUEST: 'FETCH_STATISTICS_REQUEST',
    FETCH_STATISTICS_SUCCESS: 'FETCH_STATISTICS_SUCCESS',
    FETCH_STATISTICS_FAILURE: 'FETCH_STATISTICS_FAILURE',

    POST_SUBSCRIPTION: 'POST_SUBSCRIPTION',
    POST_SUBSCRIPTION_REQUEST: 'POST_SUBSCRIPTION_REQUEST',
    POST_SUBSCRIPTION_SUCCESS: 'POST_SUBSCRIPTION_SUCCESS',
    POST_SUBSCRIPTION_FAILURE: 'POST_SUBSCRIPTION_FAILURE',

    POST_RESUME: 'POST_RESUME',
    POST_RESUME_REQUEST: 'POST_RESUME_REQUEST',
    POST_RESUME_SUCCESS: 'POST_RESUME_SUCCESS',
    POST_RESUME_FAILURE: 'POST_RESUME_FAILURE',

    POST_CONTACT_FORM: 'POST_CONTACT_FORM',
    POST_CONTACT_FORM_REQUEST: 'POST_CONTACT_FORM_REQUEST',
    POST_CONTACT_FORM_SUCCESS: 'POST_CONTACT_FORM_SUCCESS',

    COMMON_FAILURE: 'COMMON_FAILURE',
    CLEAR_TOAST:'CLEAR_TOAST'
}
export const action = (type, payload = {}) => {
    return { type, payload }
}

export const fetchTestimonials = () => action(TYPES.FETCH_TESTIMONIALS)
export const fetchBanner = () => action(TYPES.FETCH_BANNER)
export const fetchBlogs = (data) => action(TYPES.FETCH_BLOG,{data})
export const fetchClients = () => action(TYPES.FETCH_CLIENT)
export const fetchStatitics = () => action(TYPES.FETCH_STATISTICS)

export const clearToast = () => action(TYPES.CLEAR_TOAST)

export const postSubscription = (data) => action(TYPES.POST_SUBSCRIPTION, { data })
export const postResume = (data) => action(TYPES.POST_RESUME, { data })
export const postContactForm = (data) => action(TYPES.POST_CONTACT_FORM, { data })
