export const TYPES = {
    FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
    FETCH_TESTIMONIALS_REQUEST: 'FETCH_TESTIMONIALS_REQUEST',
    FETCH_TESTIMONIALS_SUCCESS: 'FETCH_TESTIMONIALS_SUCCESS',
    FETCH_TESTIMONIALS_FAILURE: 'FETCH_TESTIMONIALS_FAILURE',

    FETCH_BANNER: 'FETCH_BANNER',
    FETCH_BANNER_REQUEST: 'FETCH_BANNER_REQUEST',
    FETCH_BANNER_SUCCESS: 'FETCH_BANNER_SUCCESS',
    FETCH_BANNER_FAILURE: 'FETCH_BANNER_FAILURE',

    FETCH_BLOG: 'FETCH_BLOG',
    FETCH_BLOG_REQUEST: 'FETCH_BLOG_REQUEST',
    FETCH_BLOG_SUCCESS: 'FETCH_BLOG_SUCCESS',
    FETCH_BLOG_FAILURE: 'FETCH_BLOG_FAILURE',

    FETCH_BLOG_BY_ID: 'FETCH_BLOG_BY_ID',
    FETCH_BLOG_BY_ID_REQUEST: 'FETCH_BLOG_BY_ID_REQUEST',
    FETCH_BLOG_BY_ID_SUCCESS: 'FETCH_BLOG_BY_ID_SUCCESS',
    FETCH_BLOG_BY_ID_FAILURE: 'FETCH_BLOG_BY_ID_FAILURE',

    FETCH_NEWS: 'FETCH_NEWS',
    FETCH_NEWS_REQUEST: 'FETCH_NEWS_REQUEST',
    FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
    FETCH_NEWS_FAILURE: 'FETCH_NEWS_FAILURE',

    FETCH_NEWS_BY_ID: 'FETCH_NEWS_BY_ID',
    FETCH_NEWS_BY_ID_REQUEST: 'FETCH_NEWS_BY_ID_REQUEST',
    FETCH_NEWS_BY_ID_SUCCESS: 'FETCH_NEWS_BY_ID_SUCCESS',
    FETCH_NEWS_BY_ID_FAILURE: 'FETCH_NEWS_BY_ID_FAILURE',

    FETCH_CLIENT: 'FETCH_CLIENT',
    FETCH_CLIENT_REQUEST: 'FETCH_CLIENT_REQUEST',
    FETCH_CLIENT_SUCCESS: 'FETCH_CLIENT_SUCCESS',
    FETCH_CLIENT_FAILURE: 'FETCH_CLIENT_FAILURE',

    FETCH_STATISTICS: 'FETCH_STATISTICS',
    FETCH_STATISTICS_REQUEST: 'FETCH_STATISTICS_REQUEST',
    FETCH_STATISTICS_SUCCESS: 'FETCH_STATISTICS_SUCCESS',
    FETCH_STATISTICS_FAILURE: 'FETCH_STATISTICS_FAILURE',
    
    FETCH_ORDERS: 'FETCH_ORDERS',
    FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

    FETCH_ORDER_DETAILS: 'FETCH_ORDER_DETAILS',
    FETCH_ORDER_DETAILS_REQUEST: 'FETCH_ORDER_DETAILS_REQUEST',
    FETCH_ORDER_DETAILS_SUCCESS: 'FETCH_ORDER_DETAILS_SUCCESS',
    FETCH_ORDER_DETAILS_FAILURE: 'FETCH_ORDER_DETAILS_FAILURE', 

    FETCH_DASHBOARD:'FETCH_DASHBOARD',
    FETCH_DASHBOARD_REQUEST: 'FETCH_DASHBOARD_REQUEST',
    FETCH_DASHBOARD_SUCCESS: 'FETCH_DASHBOARD_SUCCESS',
    FETCH_DASHBOARD_FAILURE: 'FETCH_DASHBOARD_FAILURE',  

    POST_SUBSCRIPTION: 'POST_SUBSCRIPTION',
    POST_SUBSCRIPTION_REQUEST: 'POST_SUBSCRIPTION_REQUEST',
    POST_SUBSCRIPTION_SUCCESS: 'POST_SUBSCRIPTION_SUCCESS',
    POST_SUBSCRIPTION_FAILURE: 'POST_SUBSCRIPTION_FAILURE',

    POST_RESUME: 'POST_RESUME',
    POST_RESUME_REQUEST: 'POST_RESUME_REQUEST',
    POST_RESUME_SUCCESS: 'POST_RESUME_SUCCESS',
    POST_RESUME_FAILURE: 'POST_RESUME_FAILURE',

    POST_CONTACT_FORM: 'POST_CONTACT_FORM',
    POST_CONTACT_FORM_REQUEST: 'POST_CONTACT_FORM_REQUEST',
    POST_CONTACT_FORM_SUCCESS: 'POST_CONTACT_FORM_SUCCESS',

    COMMON_FAILURE: 'COMMON_FAILURE',
    CLEAR_TOAST:'CLEAR_TOAST',

    LOGIN_FORM: 'LOGIN_FORM',
    LOGIN_FORM_REQUEST: 'LOGIN_FORM_REQUEST',
    LOGIN_FORM_SUCCESS: 'LOGIN_FORM_SUCCESS',

}
export const action = (type, payload = {}) => {
    return { type, payload }
}

export const fetchTestimonials = () => action(TYPES.FETCH_TESTIMONIALS)
export const fetchBanner = () => action(TYPES.FETCH_BANNER)
export const fetchBlogs = (data) => action(TYPES.FETCH_BLOG,{data})
export const fetchBlogById = (data) => action(TYPES.FETCH_BLOG_BY_ID,{data})

export const fetchNews = (data) => action(TYPES.FETCH_NEWS,{data})
export const fetchNewsById = (data) => action(TYPES.FETCH_NEWS_BY_ID,{data})
export const fetchClients = () => action(TYPES.FETCH_CLIENT)
export const fetchStatitics = () => action(TYPES.FETCH_STATISTICS)

export const clearToast = () => action(TYPES.CLEAR_TOAST)

export const postSubscription = (data) => action(TYPES.POST_SUBSCRIPTION, { data })
export const postResume = (data) => action(TYPES.POST_RESUME, { data })
export const postContactForm = (data) => action(TYPES.POST_CONTACT_FORM, { data })
export const loginUser=(data)=>action(TYPES.LOGIN_FORM,{data})
export const fetchOrders = (data) => action(TYPES.FETCH_ORDERS,{data})
export const fetchOrderDetails = (data) => action(TYPES.FETCH_ORDER_DETAILS,{data})
export const fetchDashboard = (data) => action(TYPES.FETCH_DASHBOARD,{data})